apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
data:
  APP_NAME: "blog"
  APP_ENV: "local"
  APP_KEY: "base64:YrEeMrmPG7Zq/DFZg9hC6vwLGNZGiCrQcTaSHT48s3o="
  APP_DEBUG: "true"
  APP_URL: "http://localhost"

  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "blog"
  DB_USERNAME: "root"
  DB_PASSWORD: "glob"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DISK: "public"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"

  MEMCACHED_HOST: "127.0.0.1"
