apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  hostPath:
    path: /code
